 # 版本
version: 0.1.0


# py可执行文件名字，比如说 python3.8 、 python3 ，默认python
python_name: "python"


# 开启/关闭 debug信息显示
debug_info: False


# 自动化测试，可以选择关闭的模块
auto_setting:
  port_scan: False     # 开启/关闭 端口扫描
  cidr_scan: False     # 开启/关闭 C段扫描
  waf_scan: False      # 开启/关闭 WAF扫描
  dir_scan: False      # 开启/关闭 目录扫描
  poc_scan: False      # 开启/关闭 POC扫描


## 子域名扫描配置
sub_scan:
  brute_scan: True      # 开启/关闭 爆破扫描
  brute_thread: 1000    # 爆破域名时候的线程
  brute_fuzzy: False     # 开启/关闭 域名置换（注意：如果fuzz生成的字典较大，可能会导致爆破时间很长。）

  api_key:
    # zoomeye可以免费注册帐号密码
    # https://www.zoomeye.org/
    zoomeye_mail: ""
    zoomeye_pass: ""

    # hunter的api可免费获取，每天限量500条数据
    # https://hunter.qianxin.com/
    hunter_key: ""

    # securitytrails的api可免费获取
    # https://securitytrails.com
    securitytrails_key: ""

    # fullhunt的api可免费获取
    # https://fullhunt.io/search
    fullhunt_key: ""

    # Binaryedge免费注册获取API, 有效期只有1个月，到期之后可以再次生成，每月可以查询250次。
    # https://app.binaryedge.io/account/api
    binaryedge_key: ""

    # censys可以免费注册一个账号，填上你的账号密码即可。
    # https://search.censys.io/
    censys_username: ""
    censys_password: ""

    # fofa的api需要自费获取，因为我有key，所以就加一个吧
    # https://fofa.info/
    fofa_email: ""
    fofa_key: "2"
    fofa_size: "3000"


## 端口扫描配置
port_scan:
  timeout: 5
  thread_num : 1000
  port_range: '21,22,23,80-99,135,139,442-445,666,800,801,808,880,888,889,1000-2379,3000-10010,11115,12018,12443,14000,16080,18000-18098,19001,19080,20000,20720,21000,21501,21502,28018,20880,27017'
  skip_alive: True  # 跳过IP存活检测


# C段扫描，参数配置
cidr_scan:
  method: fofa    # 扫描方式，可选参数：fofa, system
  blacklist: [
      '微软', '阿里云', '阿里云BGP节点', '阿里云BGP服务器', '阿里巴巴', 'Microsoft', 'CDN', 'Azure', '华为', '华为云',
      '腾讯云', '网宿', 'Amazon', '运营商','世纪互联BGP数据中心', '内部网', '局域网', '对方和您在同一内部网', '亚马逊', '127.0.0.1'
  ]
  skip_alive: False     # 跳过IP存活检测
  occurrence_limit: 2   # 如果C段统计出现次数，大于1才扫描


# POC扫描，参数配置
poc_scan:
  afrog_engine: True


# 目录扫描，参数配置
dir_scan:
  threads: "30"   # 线程数
  match_code: ""  # 需要匹配的HTTP状态码
  filter_code: ""    # 从响应中过滤HTTP状态码。逗号分隔的代码和范围列表
  filter_lines: ""   # 从响应中过滤行数
  filter_world: ""   # 从响应中过滤单词
  filter_size: ""    # 从响应中过滤大小
  filter_regexp: ""  # 从响应中过滤正则关键字


# 163邮箱信息配置
smtp_server: smtp.163.com         # 邮箱服务器
smtp_port: 465                    # 端口号
send_email: ""     # 发件人邮箱账号
send_pass: ""       # 发件人邮箱授权码
rec_email: ""       # 收件人邮箱,如果有多个收件人需要使用英文逗号隔开


# 自定义user-agent
user-agent:
  - Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
  - Mozilla/5.0 (Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0
  - Mozilla/5.0 (Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0
  - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:57.0) Gecko/20100101 Firefox/57.0
  - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:58.0) Gecko/20100101 Firefox/58.0
  - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
  - Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
