# zoomeye可以免费注册帐号密码
# https://www.zoomeye.org/
zoomeye_mail:
zoomeye_pass:

# hunter的api可免费获取，每天限量500条数据
# https://hunter.qianxin.com/
hunter_key:

# fullhunt的api可免费获取
# https://securitytrails.com
securitytrails_key:

# fullhunt的api可免费获取
# https://fullhunt.io/search
fullhunt_key:

# Binaryedge免费注册获取API, 有效期只有1个月，到期之后可以再次生成，每月可以查询250次。
# https://app.binaryedge.io/account/api
binaryedge_key:

# censys可以免费注册一个账号，填上你的账号密码即可。
# https://search.censys.io/
censys_username:
censys_password:

# fofa的api需要自费获取，因为我有key，所以就加一个吧
# https://fofa.info/
fofa_email:
fofa_key:
fofa_size: 2000

# 可以免费申请一个多地ping的key
# https://api.tjit.net/user/key
cdn_key:

# 自定义user-agent
user-agent:
  - Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
  - Mozilla/5.0 (Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0
  - Mozilla/5.0 (Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0
  - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:57.0) Gecko/20100101 Firefox/57.0
  - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:58.0) Gecko/20100101 Firefox/58.0
  - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
  - Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

# 默认扫描端口
port: 21,22,23,80-99,135,139,442-445,666,800,801,808,880,888,889,1000,1010,1080,1081,1082,1118,1211,1214,1433,1888,2008,2020,2100,2375,2379,27017,3000-10010,11115,12018,12443,14000,16080,18000-18098,19001,19080,20000,20720,21000,21501,21502,28018,20880
port_thread: 600

# POC扫描引擎
# 可选参数： system, afrog
poc_setting: afrog